version: '3.3'

services:
    particl_core:
        image: i_particl_0.19.2.18
        build:
            context: particl_0.19.2.18
            dockerfile: Dockerfile
        container_name: particl_core
        volumes:
            - /var/data/particl:/data
        ports:
            - "51738:51738"
        expose:
            - 51735
            - 20792
        restart: unless-stopped
    particl_stakepool:
        image: i_particl_stakepool
        build:
            context: stakepool
            dockerfile: Dockerfile
        container_name: particl_stakepool
        volumes:
            - /var/data/stakepool:/data
        expose:
            - 9000
        depends_on:
            - particl_core
        restart: unless-stopped
    stakepool_gui:
        build:
            context: gui
            dockerfile: Dockerfile
        container_name: particl_stakepool_gui
        expose:
            - 80
        depends_on:
            - particl_stakepool
        environment:
            VIRTUAL_NETWORK: stakepool_network
            VIRTUAL_HOST: ${STAKEPOOL_GUI_HOST}
            VIRTUAL_SERVICE_NAME: "stakepool_gui"
            LETSENCRYPT_HOST: ${STAKEPOOL_GUI_HOST}
            LETSENCRYPT_EMAIL: ${STAKEPOOL_GUI_EMAIL}
        restart: unless-stopped
networks:
    default:
        external:
            name: stakepool_network
